Questão 1
Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
import numpy as np

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for element in arr1:
    print(element)

arr2: np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for element in np.nditer(arr2):
    print(element)

Questão 2
Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [ ]:
import numpy as np

def input_usuario():
    data = []

    input_string = input('Digite sua comida favorita [-1 para sair]: ')

    while input_string != '-1':
        data.append(input_string)

        input_string = input('Digite sua comida favorita [-1 para sair]: ')

    return data

def run():
    data = input_usuario()

    data_as_numpy = np.array(data)

    data_as_numpy = [element for element in data_as_numpy if element[0].lower() not in ['a', 'e','i', 'o', 'u' ]]

    print(data_as_numpy)

run()

Questão 3
Imprima a dimensão dos seguintes objetos numpy:

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
import numpy as np

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a.shape, b.shape, c.shape, d.shape)

() (5,) (2, 3) (2, 2, 3)


Questão 4
Transforme o array em uma matriz 4 por 3 utilizando numpy.

arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.

In [ ]:
import numpy as np

arr = [1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]

arr1 = np.reshape(arr, (4, 3))

print(arr1)

arr1 = np.reshape(arr, (3, 4))

print(arr1)

[['1' '2' '3']
 ['4' 'Amelia' 'Bruna']
 ['Carolina' 'Débora' 'True']
 ['False' 'False' 'True']]
[['1' '2' '3' '4']
 ['Amelia' 'Bruna' 'Carolina' 'Débora']
 ['True' 'False' 'False' 'True']]



Questão 5
Transforme o seguinte array em uma matriz 3D 3x3x3:

arr = range(27)

Deixe um comentário explicando o que significa uma matriz 3D.

In [ ]:
import numpy as np

arr = range(27)

print(np.reshape(arr, (3, 3, 3)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



Questão 6
Tente transformar o seguinte array em uma matriz 3x3x3

arr = [1, 2, 3, 4, 5, 6, 7, 8]

Funciona? Se sim, explique o motivo. Se não, explique o erro.

In [ ]:
import numpy as np

arr = [1, 2, 3, 4, 5, 6, 7, 8]

print(np.reshape(arr, (3, 3, 3)))

#Não irá funcionar pois está faltando 1 elemento no array. Assim como as tuplas, os arrays precisam homogêneos e imutáveis.


Questão 7
Percorra o seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora, percorra o mesmo array utilizando a função nditer de numpy

In [ ]:
import numpy as np

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

for i in arr:
  for j in i:
    for k in j:
      print(k)

for element in np.nditer(arr):
    print(element)

Questão 8
Percorra os indexes do seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora faça o mesmo trabalho utilizando a função ndenumerate.

In [ ]:
import numpy as np

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

for i in arr:
  for j in i:
    for k in j:
      print(k)

for index, x in np.ndenumerate(arr):
    print(x)

Questão 9
Junte os dois seguintes arrays na horizontal:

arr1 = [1, 2, 3]

arr2 = [4, 5, 6]

Depois, os junte verticalmente.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)
array([[1, 2],
       [3, 4],
       [5, 6]])
np.concatenate((a, b.T), axis=1)
array([[1, 2, 5],
       [3, 4, 6]])
np.concatenate((a, b), axis=None)
array([1, 2, 3, 4, 5, 6])




Questão 10
DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.

frutas = ['banana', 'morango, 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

In [2]:
import numpy as np
import re

frutas = np.array(['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi'])

for fruta in np.nditer(frutas):
    if len(re.findall('a|e|i|o|u', str(fruta))) == 2:
      print([fruta])

[array('uva', dtype='<U8')]
[array('kiwi', dtype='<U8')]



Questão 11
a) Tranforme o seguinte array 2D em dois arrays 2D:

arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(np.reshape(arr, (4, 2)))

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.reshape(arr2, (3, 3)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Questão 12
DESAFIO: Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.

In [ ]:

import numpy as np

#[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

arr = np.array(['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False])

print(np.where(np.char.isalpha(arr)))

students = np.reshape(arr, (4, -1))

print(students)

column1, column2 = np.hsplit(students.reshape(-1, 8), 2)

print(column1)

print(column2)

def delete_gender(row):
    if int(row[1]) < 14:
        row[2] = None

    return row

print(np.apply_along_axis(delete_gender, axis=1, arr=column1))